python-packages/securesync/urls.py
"""
"""
from django.conf import settings
from django.conf.urls import include, patterns, url


urlpatterns = patterns('securesync.views',
    url(r'^', include('securesync.devices.urls')),
    url(r'^', include('securesync.engine.urls')),
)

python-packages/securesync/devices/models.py
"""
"""
import datetime
import logging
import uuid
from annoying.functions import get_object_or_None

from django.conf import settings
from django.contrib.auth.models import check_password
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django.db import models, transaction
from django.db.models import Q
from django.utils.text import compress_string
from django.utils.translation import ugettext_lazy as _

from .. import ID_MAX_LENGTH, IP_MAX_LENGTH, VERSION
from .. import crypto
from ..engine.models import SyncedModel, SyncedModelManager
from fle_utils.general import get_host_name
from fle_utils.django_utils import validate_via_booleans, ExtendedModel


class RegisteredDevicePublicKey(ExtendedModel):
    public_key = models.CharField(max_length=500, help_text="(This field will be filled in automatically)")
    zone = models.ForeignKey("Zone")
    created_timestamp = models.DateTimeField(auto_now_add=True, null=True, default=None)  # Null for oldies
    used_timestamp = models.DateTimeField(null=True, default=None)

    class Meta:
        app_label = "securesync"

    def __unicode__(self):
        out_str = u"%s... (Zone: %s)" % (self.public_key[0:5], self.zone)
        out_str += (u"; created on %s" % self.created_timestamp) if self.created_timestamp else ""
        out_str += (u"; used on %s" % self.used_timestamp) if self.used_timestamp else ""
        return out_str

    def use(self):
        # Never should get called if timestamp
        assert not self.used_timestamp, "Cannot reuse public key registrations"
        self.used_timestamp = datetime.datetime.now()
        self.save()

    def is_used(self):
        return self.used_timestamp is not None


class UnregisteredDevice(ExtendedModel):
    """
    Bare list of all unregistered devices that 'ping' us with a device ID
    """
    id = models.CharField(primary_key=True, max_length=ID_MAX_LENGTH, editable=False)


class UnregisteredDevicePing(ExtendedModel):
    """
    Whenever we receive a session request from an unregistered device,
    we increase our counter
    """
    device = models.ForeignKey("UnregisteredDevice", unique=True)
    npings = models.IntegerField(default=0)
    last_ip = models.CharField(max_length=IP_MAX_LENGTH, blank=True)
    last_ping = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return u"%s: %s pings, last on %s from %s" % (self.device.id, self.npings, self.last_ping, self.last_ip)

    @classmethod
    def record_ping(cls, id, ip):
        """
        We received a failed request to create a session; record that 'ping' in our DB
        """
        try:
            # Create the log (if necessary), update, and save
            # TODO: make a base class (in django_utils) that has get_or_initialize, and use that
            #   to shorten things here
            (cur_device, _) = UnregisteredDevice.objects.get_or_create(id=id)
            (cur_log, _) = cls.get_or_initialize(device=cur_device)  # get is safe, because device is unique

            cur_log.npings += 1
            cur_log.last_ip = ip
            cur_log.save()

        except Exception as e:
            # Never block functionality
            logging.error("Error recording unregistered device ping: %s" % e)


class DeviceMetadata(ExtendedModel):
    device = models.OneToOneField("Device", blank=True, null=True)
    is_trusted = models.BooleanField(default=False)
    is_own_device = models.BooleanField(default=False)
    is_demo_device = models.BooleanField(default=False)
    counter_position = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = "Device metadata"
        app_label = "securesync"

    def __unicode__(self):
        return u"(Device: %s)" % (self.device)


class Zone(SyncedModel):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)

    class Meta:
        app_label = "securesync"

    #@central_server_only  # causes circular loop, to include here
    def get_org(self):
        """
        Reverse lookup of organization containing this zone.
        """
        orgs = self.organization_set.all()
        assert orgs.count() <= 1, "Zone must be contained by 0 or 1 organization(s)."

        return orgs[0] if orgs else None

    def is_member(self, device):
        """
        """
        try:
            return ChainOfTrust(zone=self, device=device).verify()
        except:
            return False

    @validate_via_booleans
    def validate(self):
        """
        Nothing to verify--ANYBODY can make a zone.  The question is
        if you can convince anybody else to join it :P
        """
        return True

    @classmethod
    def get_headless_zones(cls):
        """
        Method for getting all zones that aren't connected to at least one organization.
        """
        # Must import inline (not in header) to avoid import loop
        return Zone.objects.filter(organization=None)

    def __unicode__(self):
        return self.name


class DeviceZone(SyncedModel):
    device = models.ForeignKey("Device", unique=True)
    zone = models.ForeignKey("Zone", db_index=True)
    revoked = models.BooleanField(default=False)
    max_counter = models.IntegerField(blank=True, null=True)

    class Meta:
        app_label = "securesync"

    @validate_via_booleans
    def validate(self):
        """
        Verify that it was created by a trusted server (old-school),
        or that it has an invitation backing the devicezone (new-school)
        """
        if self.signed_by.is_trusted():
            return True
        invitation =  get_object_or_None(ZoneInvitation, used_by=self.device, zone=self.zone)
        return self.device == self.signed_by and invitation and invitation.verify()

    def __unicode__(self):
        return u"Device: %s, assigned to Zone: %s" % (self.device, self.zone)


class DeviceManager(SyncedModelManager):

    class Meta:
        app_label = "securesync"

    def by_zone(self, zone):
        # get Devices that belong to a particular zone, or are a trusted authority
        return self.filter(Q(devicezone__zone=zone, devicezone__revoked=False) |
            Q(devicemetadata__is_trusted=True))


class Device(SyncedModel):
    name = models.CharField(max_length=100, blank=True)
    description = models.TextField(blank=True)
    public_key = models.CharField(max_length=500, db_index=True)
    version = models.CharField(max_length=len("10.10.100"), default="0.9.2", blank=True); version.minversion="0.9.3"  # default comes from knowing when this feature was implemented!

    objects = DeviceManager()
    all_objects = DeviceManager(show_deleted=True)

    key = None
    own_device = None  # cached property, shared globally.

    class Meta:
        app_label = "securesync"

    def set_key(self, key):
        assert isinstance(key, crypto.Key), "key must be a crypto Key object"
        self.public_key = key.get_public_key_string()
        self.key = key

    def get_key(self):
        if not self.key:
            if self.get_metadata().is_own_device:
                self.key = crypto.get_own_key()
            elif self.public_key:
                self.key = crypto.Key(public_key_string=self.public_key)
        return self.key

    def _hashable_representation(self):
        fields = ["signed_version", "name", "description", "public_key"]
        return super(Device, self)._hashable_representation(fields=fields)

    def get_metadata(self):
        try:
            return self.devicemetadata
        except DeviceMetadata.DoesNotExist:
            return DeviceMetadata(device=self)

    def get_counter_position(self):
        """
        """
        if not self.id:
            return 0

        else:
            return self.get_metadata().counter_position

    def set_counter_position(self, counter_position, soft_set=False):
        metadata = self.get_metadata()
        if not metadata.device.id:  # only happens if device has not been saved yet.  Should be changed to self.id
            return

        # It's often convenient to reset the position ONLY if the new counter position
        #   is higher than the old.  So, let people be lazy--but need to send in a flag,
        #   so it's clear that something a bit unusual is happening in a "set"
        if soft_set and self.signed_by.get_counter_position() >= counter_position:
            return

        assert counter_position >= metadata.counter_position, "You should not be setting the counter position to a number lower than its current value!"
        metadata.counter_position = counter_position
        metadata.save()


    @transaction.commit_on_success
    def increment_counter_position(self):
        metadata = self.get_metadata()
        if not metadata.device.id:
            return 0
        metadata.counter_position += 1
        metadata.save()
        return metadata.counter_position

    def full_clean(self, *args, **kwargs):
        # TODO(jamalex): we skip out here, because otherwise self-signed devices will fail
        pass

    def get_version(self):
        """
        Get this property through an accessor function,
        so that we can guarantee that the DB-stored version
        matches the hard-coded software version.
        """
        own_device = Device.get_own_device()
        if self == own_device and self.version != VERSION:
            self.version = VERSION
            self.save()
        return self.version

    @classmethod
    def get_default_version(cls):
        """Accessor method to probe the default version of a device (or field)"""
        return cls._meta.get_field("version").default

    @classmethod
    def get_own_device(cls):
        if not cls.own_device:
            devices = DeviceMetadata.objects.filter(is_own_device=True)
            if devices.count() == 0:
                cls.own_device = cls.initialize_own_device() # why don't we need name or description here?
            else:

python-packages/securesync/templates/securesync/register_public_key_client.html
{% extends base_template %}
{% load i18n %}

{% block register_active %}active{% endblock register_active %}

{% block title %}{% trans "Register a Device" %} {{ block.super }}{% endblock title %}

{% block headcss %}{{ block.super }}
    <style>
        .chunk-container {
            margin: 15px;
            padding: 10px 30px 25px 30px;
        }
        .well-wrapper {
            border: 1px solid rgb(226, 226, 226);
            background-color: rgb(247, 247, 247);
            border-radius: 10px;
        }
        .blurb {
            margin-left: 20px;
            margin-right: 20px;
        }
        .normalized-list {
            margin-left: 50px;
            list-style-type: circle;
        }
        .normalized-list > li {
            font-size: 15px;
            line-height: 1.5em;
        }
        .normal-size {
            font-size: 14px;
        }
        .normalized-table {
            margin:25px 25px 0px 25px;
        }
        .normalized-table > tbody > tr > th {
            font-size: 15px;
        }
        .nudge-right {
            margin-left: 20px;
        }
        .table-header > td > h3 {
            margin-bottom: 0px;
        }
    </style>
{% endblock headcss %}

{% block headjs %}{{ block.super }}
    <script>

        function reload() {
            window.location.reload();
        }

        $(function() {
            $(".refresh-link").click(reload);
        });

        function auto_register() {
            // Disable and show message
            $("#one-click-register").toggleClass("disabled", true);
            show_message("info", "{% trans 'Contacting central server to register; page will reload upon success.' %}");

            doRequest("{{ auto_registration_url }}", null, {dataType: "jsonp"})
                .success(function() {
                    show_message("success", "Auto-registered.");
                    window.location.reload();
                })
                .fail(function(a, b) {
                    // Re-enable
                    $("#one-click-register").toggleClass("disabled", false);
                });
        }
    </script>
{% endblock headjs %}

{% block content %}
    {% if not unregistered %}
        <h2>{% trans "Device registration" %}</h2>
    {% endif %}
    {% if error_msg %}
        {% comment %}Translators: Please do not edit the variable text: %(command)s {% endcomment %}
        <p>{% blocktrans with command="<b>python manage.py update</b>" %}Sorry, there was an error during registration. Please make sure your device is fully up to date (run {{ command }} and then stop/start the server).{% endblocktrans %}</p>
        <p>{% trans "The error message was:" %} <b>{{ error_msg }}</b></p>
    {% endif %}

    {% if newly_registered %}
    <p>{% trans "Congratulations, this device has now been registered." %}</p>
    {% endif %}

    {% if already_registered %}
    <p>{% trans "This device has already been registered." %}</p>
    {% endif %}

    {% if no_internet %}
    <p>{% trans "The device needs to have internet access when first being registered. Please ensure it is connected to the internet, and then" %} <a href="." class="refresh-link">{% trans "refresh this page" %}</a>.</p>
    {% endif %}


    {% if unregistered %}
    <div class="chunk-container">
        <h2>{% trans "What is device registration?" %}</h2>
        <p class="normal-size" style="padding: 0px 40px 0px 40px;">
            {% trans "Once you register your installation with us, your data can be synced to our online repository when KA Lite has access to the Internet. This is a good thing! Here's why:" %}
        </p>
        <ul class="normalized-list" style="padding: 0px 40px 0px 40px;">
            <li>{% trans "Your data will be backed up online" %}</li>
            <li>{% trans "You can login online and review your usage data" %}</li>
            <li>{% trans "Our team can use this data to objectively assess the impact our work is having around the world!" %}</li>
        </ul>
    </div>

    <div class="chunk-container">
        <h2>{% trans "Ready to register? You have two options:" %}</h2>

        <table class="normalized-table">
            <tr class="table-header">
                <td width="50%"><h3 class="blurb">{% trans "One-click registration (no online access to data)" %}</h3></td>
                <td width="50%"><h3 class="blurb">{% trans "Register with online access to data!" %}</h3></td>
            </tr>
            <tr>
                <td>
                    <p class="blurb">
                        <strong>{% trans "The perfect option for individual users who just want to get KA Lite up and running fast and don't need online access to data." %}</strong>
                    </p>
                    <p class="blurb">
                        {% trans "This allows you to get the registration process over in one-click without worrying about creating a login that you're never going to use." %}
                    </p>
                </td>
                <td>
                    <p class="blurb">
                        <strong>{% trans "The perfect option for adminstrators of larger projects!" %}</strong>
                    </p>
                    <p class="blurb">
                        {% trans "This option will walk you through the process of creating a login to our website that will allow you access your uploaded data and connect multiple installations to the same account." %}
                    </p>
                </td>
            </tr>
            <tr>
                <td>
                    <a class="green_button nudge-right" id="one-click-register" href="javascript:auto_register()">{% trans "One-click registration now!" %}</a>
                </td>
                <td>
                    <a class="green_button nudge-right" id="online-register" href="{{ classic_registration_url }}">{% trans "Register with an online account now!" %}</a>
                </td>
            </tr>
        </table>

    </div>


    {% endif %}
{% endblock content %}

python-packages/securesync/templates/securesync/register_public_key_server.html
{% extends base_template %}
{% load i18n %}
{% load staticfiles %}

{% block title %}{% trans "Register device to a sharing network" %} {{ block.super }}{% endblock title %}

{% block headjs %}
    <script type="text/javascript" src="{% static 'js/purl.js' %}"></script>
    <script>
        $(function() {
            var cururl = $.url(window.location);
            var public_key = null;
            var params = cururl.param();
            for (key in params) {
                if (key.length > 50 && cururl.param(key) == "") {
                    public_key = key;
                    break;
                } else if (params[key].length > 50) {
                    public_key = params[key];
                    break;
                }
            }
            $("#id_public_key").val(decodeURIComponent(public_key));
            $('#id_public_key').attr('readonly',true);
            $('#id_public_key').css('color','grey');
        });
    </script>
{% endblock headjs %}

{% block content %}
    <h2>{% trans "Register a device" %}</h2>
    <form method="post" class="basic-form">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register" class="submit"/>
    </form>
{% endblock content %}